import { motion } from "framer-motion";
import { fadeUpVariant } from "../lib/animations";

export default function TermsAndConditions() {
  return (
    <section className="pt-32 pb-20 px-6 max-w-4xl mx-auto bg-white min-h-screen">
      <motion.div
        variants={fadeUpVariant}
        initial="hidden"
        animate="visible"
      >
        <h1 className="text-4xl md:text-5xl font-headline font-bold mb-8 tracking-tight text-on-surface">
          Terms and Conditions
        </h1>
        <p className="text-on-surface-variant mb-8 text-sm">
          Last Updated: {new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}
        </p>

        <div className="prose prose-lg prose-slate text-on-surface/80 max-w-none space-y-6">
          <p>
            These Terms and Conditions constitute a legally binding agreement made between you, whether personally or on behalf of an entity (“you”) 
            and Oh My Hindustan ("OMH", “we”, “us”, or “our”), concerning your access to and use of the ohmyhindustan.in website as well as 
            any other media form, media channel, mobile website or mobile application related, linked, or otherwise connected thereto.
          </p>
          <p>
            You agree that by accessing the Site, you have read, understood, and agreed to be bound by all of these Terms and Conditions. 
            IF YOU DO NOT AGREE WITH ALL OF THESE TERMS AND CONDITIONS, THEN YOU ARE EXPRESSLY PROHIBITED FROM USING THE SITE AND YOU MUST DISCONTINUE USE IMMEDIATELY.
          </p>

          <h2 className="text-2xl font-bold text-on-surface mt-10 mb-4 font-headline">1. User Representations</h2>
          <p>
            By using the Site, you represent and warrant that:
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>All registration information you submit will be true, accurate, current, and complete.</li>
            <li>You will maintain the accuracy of such information and promptly update such registration information as necessary.</li>
            <li>You have the legal capacity and you agree to comply with these Terms and Conditions.</li>
            <li>You will not access the Site through automated or non-human means, whether through a bot, script, or otherwise.</li>
          </ul>

          <h2 className="text-2xl font-bold text-on-surface mt-10 mb-4 font-headline">2. Citizen Journalism & Content Ownership</h2>
          <p>
            OMH empowers every Indian to report, publish, and earn. By posting stories, videos, or articles on the platform, you retain full ownership 
            of your content. However, you grant OMH a worldwide, non-exclusive, royalty-free license to use, reproduce, and display your content 
            in connection with the service.
          </p>
          <p>
            You are solely responsible for your content and the consequences of submitting and publishing your content on the Services. 
            You affirm, represent, and warrant that you own or have the necessary licenses, rights, consents, and permissions to publish the content you submit.
          </p>

          <h2 className="text-2xl font-bold text-on-surface mt-10 mb-4 font-headline">3. Creator Revenue and Zero Algorithms</h2>
          <p>
            OMH is committed to Expression Without Barriers. We do not use hidden algorithms to suppress your voice.
            Eligible creators are entitled to a 60% revenue share based on the engagement and advertising revenue generated by their content. 
            Specific payout terms, thresholds, and conditions will be outlined in the Creator Dashboard and are subject to change.
          </p>

          <h2 className="text-2xl font-bold text-on-surface mt-10 mb-4 font-headline">4. Prohibited Activities</h2>
          <p>
            You may not access or use the Site for any purpose other than that for which we make the Site available. The Site may not be used in connection with any commercial endeavors except those that are specifically endorsed or approved by us.
          </p>
          <ul className="list-disc pl-6 space-y-2">
            <li>Systematically retrieve data or other content from the Site to create or compile, directly or indirectly, a collection, compilation, database, or directory without written permission from us.</li>
            <li>Make any unauthorized use of the Site, including collecting usernames and/or email addresses of users by electronic or other means for the purpose of sending unsolicited email.</li>
            <li>Use the Site to advertise or offer to sell goods and services without authorization.</li>
            <li>Publish fake news, hate speech, or content that incites violence. As a journalism platform, strict adherence to truth and community guidelines is required.</li>
          </ul>

          <h2 className="text-2xl font-bold text-on-surface mt-10 mb-4 font-headline">5. Contact Information</h2>
          <p>
            In order to resolve a complaint regarding the Site or to receive further information regarding use of the Site, please contact us at support@ohmyhindustan.in.
          </p>
        </div>
      </motion.div>
    </section>
  );
}
